name: CI for Selenium Python Project

on:
  push:
    branches:
      - stable  # Replace 'stable' with your stable branch name (e.g., 'main', 'master')
  pull_request:
    branches:
      - stable  # This will trigger the workflow on pull requests targeting the stable branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt

      - name: Run PyTest
        run: |
          pytest --maxfail=1 --disable-warnings --html=report.html  # Run your tests

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.html  # Path to your generated report
